### ISSUE TITLE
[BUG] Anime cards overlaps making one of them jump infinitely.

### ISSUE THREAD

**Issue by Josexv1** [wearrrrr/HaiKei#12]
On the home, if you point your mouse in the black part in the middle of 2 cards, one or both of them will jump forever.

In the image you can see one card is focused and tilted, the card will be in both status at the same time.

![image](https://user-images.githubusercontent.com/12077848/213829193-19697659-abd1-44f2-a827-7219a143c515.png)

I suggest to use other form of focus since this one is a bit annoying to be honest.

**Comment by wearrrrr** [comment]
I'll probably just change the colors and maybe add some other change, but I'm likely going to remove the tilt very soon

**Comment by wearrrrr** [comment]
The tilt has been removed, so this shouldn't be an issue, closing now, but feel free to reopen!
