### ISSUE TITLE
redis error : Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by bugbounted** [wearrrrr/HaiKei#22]
Hi [wearr](https://github.com/wearrrrr),
after deployed on render.com as new web service getting Error: connect ECONNREFUSED 127.0.0.1:6379 at runtime many time .
please make changes on current branch for set env var for redis url , because in render or any production containers redis can made & access using internal redis url like redis://red-cfiifd1a6gdq1k0a7b40:6379
waiting for your response
finest regards

**Comment by wearrrrr** [comment]
Hello! My apologies for not replying sooner, I will add the ability to make the redis address a .env variable soon, however you can also just manually set the url in the index.js file! 
Cheers!

**Comment by wearrrrr** [comment]
I'm going to close this for now, however soon I will also make redis optional!
