### ISSUE TITLE
Wrong username password 

### ISSUE THREAD

**Issue by Naiml007** [wearrrrr/HaiKei#31]
![Screenshot_2023-02-27-00-08-26-766_com android chrome](https://user-images.githubusercontent.com/90306726/221428396-9c527940-2003-4273-aa2c-816b8c048aa5.jpg)

**Comment by Naiml007** [comment]
![Uploading Screenshot_2023-02-27-00-09-50-634_com.android.chrome.jpg…]()

**Comment by Naiml007** [comment]
![Screenshot_2023-02-27-00-09-50-634_com android chrome](https://user-images.githubusercontent.com/90306726/221428467-9889eec5-70f9-4364-9dfb-3bfaef075eaa.jpg)

**Comment by wearrrrr** [comment]
Interesting, can you give me some more info, like what you are trying to host with?

**Comment by wearrrrr** [comment]
The issue comes from your redis username or password being wrong, just check your REDIS_URL env variable!

**Comment by Naiml007** [comment]
IDE not hosting replit.com

**Comment by wearrrrr** [comment]
Your issue is coming from not having redis configured properly, I'll work on making redis optional very soon, because that seems to not work with replit

**Comment by Naiml007** [comment]
What is this name: HKSECURITY for?
![IMG_20230227_002233](https://user-images.githubusercontent.com/90306726/221429208-45c28c94-7883-477e-8f6c-091013ffb6c1.jpg)

**Comment by wearrrrr** [comment]
.HKSECURITY is the cookie authentication secret, I'd advise you to set one in the .env on your deployment

**Comment by Naiml007** [comment]
![IMG_20230227_003006](https://user-images.githubusercontent.com/90306726/221429528-15fe5223-77c5-427f-900c-8d15652142be.jpg)

Redis web
![Screenshot_2023-02-27-00-30-47-456_com android chrome](https://user-images.githubusercontent.com/90306726/221429576-27213435-9a09-483f-9be5-0728f042c82b.jpg)

**Comment by wearrrrr** [comment]
Seemingly there is a username and password you need to pass in also

**Comment by Naiml007** [comment]
Yeah redis username and password

**Comment by Naiml007** [comment]
How do I pass that

**Comment by wearrrrr** [comment]
The redis_url parameter should be correct, make sure you can actually connect to the server outside of HaiKei, if you can then ill need to look into it

**Comment by Naiml007** [comment]
Thnx bro I fix it 
![Screenshot_2023-02-27-08-43-39-444_com android chrome](https://user-images.githubusercontent.com/90306726/221461109-96e499a1-1961-47ae-8ab3-49f2eca61ba3.jpg)

Add render.com link in Ur redme.md 
![Screenshot_2023-02-27-08-43-57-686_com android chrome](https://user-images.githubusercontent.com/90306726/221461189-f7ed3b8d-81c8-4dbf-ac82-0572b79c0f1f.jpg)
