### ISSUE TITLE
Help API consumet error 

### ISSUE THREAD

**Issue by Naiml007** [wearrrrr/HaiKei#32]
![Screenshot_2023-02-27-11-51-18-167_com android chrome](https://user-images.githubusercontent.com/90306726/221485044-67cb36ed-72cf-49fa-a50c-c38a9f4be338.jpg)

**Comment by wearrrrr** [comment]
A 403 error typically indicates that for some reason or another, the IP address of the machine hosting haikei (and by extension requesting consumet) is forbidden, it looks like you are using redis, in which case it would help if you ran `curl https://api.consumet.org/meta/anilist/info/139630` and sent me the output, thank you!

**Comment by Naiml007** [comment]
![Screenshot_2023-02-27-12-23-07-393_com android chrome](https://user-images.githubusercontent.com/90306726/221489686-c7ba889a-ca2d-4800-856e-89c1dbea3802.jpg)

![Screenshot_2023-02-27-12-22-09-597_com android chrome](https://user-images.githubusercontent.com/90306726/221489791-29b2472b-0deb-44ee-9d01-92ab84bc0702.jpg)

![Screenshot_2023-02-27-12-19-57-275_com android chrome](https://user-images.githubusercontent.com/90306726/221489716-a63d13d8-a250-4d0d-afb9-a18019222821.jpg)

**Comment by Naiml007** [comment]
![Screenshot_2023-02-27-12-25-56-673_com android chrome](https://user-images.githubusercontent.com/90306726/221490229-e41d6b4a-708c-4a29-999d-c4e5b48f4614.jpg)

**Comment by wearrrrr** [comment]
"just a moment.." under cloudflare means that the IP has been banned with consumet as far as I know, you will need to host your own or use https://api.haikei.xyz, I'll close this issue if everything is resolved

**Comment by Naiml007** [comment]
Ok

**Comment by Naiml007** [comment]
![Screenshot_2023-02-27-13-12-56-195_com android chrome](https://user-images.githubusercontent.com/90306726/221498175-93ea3ff0-1b90-44d2-ba12-2a06e882ce39.jpg)

**Comment by Naiml007** [comment]
Again same error 
![Uploading Screenshot_2023-02-27-13-13-51-264_com.android.chrome.jpg…]()

**Comment by Naiml007** [comment]
Again same error

![Screenshot_2023-02-27-13-13-51-264_com android chrome](https://user-images.githubusercontent.com/90306726/221498268-5b305c80-e921-4dcd-821b-190a036ed5d9.jpg)

**Comment by wearrrrr** [comment]
i don't control api.consumet.org, you can clearly see that it is still trying to access that domain, unfortunately replit is restricted on accessing consumet because of ddos attacks, im going to close this issue now

**Comment by Naiml007** [comment]
Only one piece can be seen

**Comment by wearrrrr** [comment]
I've told you the issue multiple times, I'll make some changes tomorrow to make it more compatible with redis, but for now it's just waiting because I need to sleep

**Comment by Naiml007** [comment]
Sorry good night
