### ISSUE TITLE
How to start build using npm run build or yarn ?

### ISSUE THREAD

**Issue by gusfing** [wearrrrr/HaiKei#36]

**Comment by TropicLegend** [comment]
You can look into the [docs](https://github.com/wearrrrr/HaiKei/tree/main/docs). It's described there.

**Comment by wearrrrr** [comment]
Yes the docs specify that you use yarn to build get everything working! :)

**Comment by TropicLegend** [comment]
it's working but you need to provide and configure your own HLS proxy.
You can change it in public/js/af/sources.js
